### ISSUE TITLE
Significance of  additional scheme "local"

### ISSUE THREAD

**Issue by AmitavaHazra** [AmitavaHazra/MvcMovieSCIM#5]
One thing I observed that debugging from postman is possible only when we are adding an additional authentication scheme "local" (can be with any name) along with "scim".
  [Authorize(AuthenticationSchemes = "scim,local")]

Also corresponding entry in startup.cs as per your direction.

Can you please tell me what is exactly helping so that we are able to debug ?

**Comment by AmitavaHazra** [comment]
@opatey ,
Kindly explain above one. Please..

**Comment by opatey** [comment]
Hi @AmitavaHazra - you need to familiarise yourself with .Net Authentication Schemes:
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/?view=aspnetcore-3.1

They provide different mechanisms for proving the identity of the agent making a request. There is no way that you can prove your identity to the endpoint with `scim` scheme, because you cannot pretend to be Microsoft's STS (security token service) and issue yourself a bearer token (you do not have their private key to generate valid token signatures).

However, what you _can_ do is specify a second way to prove your identity to the endpoint - the `local` authentication scheme. This is a simpler, symmetrically signed bearer token, for which you know the symmetric secret and can therefore generate valid tokens.

So when you remove `local`, you are telling your endpoint not to accept bearer tokens that you know how to generate.

Some other useful reading would be jwt.io's introduction to JWTs and Bearer authorization:
https://jwt.io/introduction/

and also the difference between symmetric and asymmetric algorithms for signing (which will hopefully explain why you can generate valid tokens for `local`, but not `scim` authentication schemes):
https://medium.com/@ealtili/cryptography-encryption-hash-functions-and-digital-signature-101-298a03eb9462

**Comment by AmitavaHazra** [comment]
@opatey ,

Thanks for your information. I will start gathering those knowledge.
